// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjlvpwsehkkqvsyzrfda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqbHZwd3NlaGtrcXZzeXpyZmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODY4MjIsImV4cCI6MjA2ODA2MjgyMn0.dU885tmG1DRaV-yEDmqrsyRhYycw3m6OQ4phFuq7wf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});